version: '3.7'

services:

    website:
        build:
            context: .
        ports:
            - 80:80

    unit-tests:
        environment:
            SELENIUM_HOST: selenium
            SELENIUM_PORT: 4444
        volumes:
            - "$PWD:/app"
        build:
            context: .
            dockerfile: rspec.dockerfile
        command:
            - --pattern
            - /app/spec/unit/*_spec.rb

    selenium:
        image: selenium/standalone-chrome-debug
        ports:
            - 4444:4444
            - 5901:5900
